name: Build Binaries

on:
  release:
    types: [created]

jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install Poetry
      uses: snok/install-poetry@v1
    - uses: actions/cache@v3
      name: Define a cache for the virtual environment based on the dependencies lock file
      with:
        path: ./.venv
        key: venv-${{ hashFiles('poetry.lock') }}
    - name: Install Dependencies
      run: poetry install --with=build
    - name: Build Binaries
      run: poetry run build
    - name: Upload the artifacts
      uses: AButler/upload-release-assets@v3.0
      with:
        files: 'dist/bambu_timelapse_downloader/*'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
