name: Build Binaries

on:
  push:
    branches: ["master"]
  release:
    types: [created]

jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          # - windows-latest
          # - macos-latest

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install Poetry
      uses: snok/install-poetry@v1
    - name: Setup Project and Build Binary
      run: |
        poetry install --with=build --no-interaction --no-root
        poetry run build
    - name: Upload the artifacts
      uses: skx/github-action-publish-binaries@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: 'dist/bambu_timelapse_downloader/*'
